# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"


gem 'rspec' , '3.5.0'
gem 'selenium-webdriver'
gem 'cucumber', '2.4.0'
gem 'rspec-expectations', '~> 3.5.0'
gem 'appium_console', '2.0.1'
gem 'appium_lib', '8.0.2'
